### ISSUE TITLE
Chinese cannot be entered

### ISSUE THREAD

**Issue by sohero** [Eugeny/tabby#5765] opened 2022-02-15 05:37 UTC
Version: 1.0.172
Platform: Windows x64 10.0.19044
Plugins: none
Frontend: xterm

命令行没法输入汉字

----

Can't enter Chinese characters on the command line

**Comment by lanzhiquan** [comment] 2022-02-15 06:41
不知道为什么搜狗输入法不适配，用微软拼音是可以的

**Comment by Alex-duzhichao** [comment] 2022-02-21 03:36
https://user-images.githubusercontent.com/9667107/154884362-3f6f12b4-1daa-4722-adbf-6a79c0443da5.MP4

@Eugeny Hi, I have recorded a demo video for this problem.  As the video shows, after input using Sogou input method, the text was swallowed by tabby. I think this issue is very urgent because almost every chinese programmer is using the Sogou IME. So would you fix this problem as soon as possible?  Thank you for the awesome work.
P.S. you can install Sogou IME using winget: `winget install Sogou.SogouInput`

**Comment by sswangifly** [comment] 2022-03-01 12:06
I got the same problem, hope fix this quickly.

**Comment by Eugeny** [comment] 2022-03-12 20:15
Duplicate of #4999

**Closed by Eugeny** 2022-03-12 20:15 UTC
Labels: T: Bug, S: Confirmed
