### ISSUE TITLE
Scrolling shell up/down in Terminus

### ISSUE THREAD

**Issue by snwagh** [Eugeny/tabby#1372] opened 2019-08-09 16:06 UTC
Is it possible to add a hotkey to scroll the terminal up/down (specifically line up/line down) in classical UNIX termianl fashion? In particular, the equivalent of `cmd + up_arrow: line up` on a Mac Shell.

**Comment by Alex-duzhichao** [comment] 2022-07-19 08:48
@Eugeny Hi, is there any progress about this feature?  
Scroll terminal is frequently used in many people's day-to-day work. So add a hotkey to it is very necessary. 
Thank you very much.

**Comment by Eugeny** [comment] 2022-07-26 16:49
Not done yet, sorry. Duplicate of #194

**Closed by Eugeny** 2022-07-26 16:49 UTC
Labels: T: Enhancement
