### ISSUE TITLE
Feature request: Reorder profiles

### ISSUE THREAD

**Issue by bdr99** [Eugeny/tabby#6427] opened 2022-05-17 01:09 UTC
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to change the order of profiles. If there is a way, I haven't been able to find it.

**Describe the solution you'd like**
It would be great if we could drag and drop profiles to reorder them.

**Describe alternatives you've considered**
I could reorder the profiles by manually editing the config file, but this is not very user-friendly.

**Additional context**
N/A

**Comment by Eugeny** [comment] 2022-05-26 10:57
Duplicate of #3059

**Closed by Eugeny** 2022-05-26 10:57 UTC
