### ISSUE TITLE
send messages broadcast to multiple terminals ?

### ISSUE THREAD

**Issue by FatuityCookie** [Eugeny/tabby#5343] opened 2021-12-31 01:15 UTC

**Comment by tulpenhaendler** [comment] 2022-01-28 14:14
+1
would be great to arrange terminals in groups and then broadcast to a specific group

**Comment by work-chausat** [comment] 2022-07-27 16:41
+1

**Comment by Eugeny** [comment] 2022-11-01 16:18
Duplicate of #5193

**Closed by Eugeny** 2022-11-01 16:18 UTC
