### ISSUE TITLE
Keyword Highlighting in Terminal

### ISSUE THREAD

**Issue by davixd** [Eugeny/tabby#5515] opened 2022-01-17 21:30 UTC
### Discussed in https://github.com/Eugeny/tabby/discussions/5514

<div type='discussions-op-text'>

<sup>Originally posted by **davixd** January 17, 2022</sup>
Hello guys,
first of all its a great project! Is it possible to integrate Keyword Highlighting in Tabby?

As for example here described:
https://saravanaj.github.io/2021/07/15/mobaxterm-like-keyword-highlighting-in-linux-terminal/

This would be great.

Many thanks in advance!

Best regards
David</div>

**Comment by Eugeny** [comment] 2022-01-17 21:46
Duplicate of #632

**Closed by Eugeny** 2022-01-17 21:46 UTC
