### ISSUE TITLE
Latest version following shell directory does not take effect

### ISSUE THREAD

**Issue by zxiaozhou** [Eugeny/tabby#6339] opened 2022-05-03 04:04 UTC
**Describe the solution you'd like**
1. Latest version following shell directory does not take effect
2. I have followed the tutorial Settings
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/62740686/166403396-484d4ee9-f920-4268-b63d-14e4547346d6.png">

**Comment by Eugeny** [comment] 2022-05-10 03:57
Duplicate of #6260

**Closed by Eugeny** 2022-05-10 03:57 UTC
