### ISSUE TITLE
I just lost all my stored ssh sessions. I want to die.

### ISSUE THREAD

**Issue by brunolabozzetta** [Eugeny/tabby#6507] opened 2022-05-27 15:26 UTC
Hi!

I'm currently running Ubuntu 22.04, and just lost all my ssh sessions.

It just happened when i cancel a connection several times with a host pressing scape.

I can see the sessions stored in vault but i lost all my groups and the possibility to use the shortcuts to access those hosts.

There is any chance to re-import these sessions using the vault file?

Thanks a lot.

Version: 1.0.177
Platform: Linux x64 5.15.0-33-generic
Plugins: none
Frontend: xterm

**Comment by Brskt** [comment] 2022-05-28 09:25
Hello,

I'm experiencing the same issue with the Windows app, happened me twice.
This is very annoying to reconfigure all the configuration app (yes, it does reset all the configuration and not only the SSH sessions).

**Comment by MostHated** [comment] 2022-05-28 18:24
I just updated on 22.04 and changed a setting and now the terminal won't open at all. I am afraid to look, as I fear the same thing might have happened to me as well.

**Comment by brunolabozzetta** [comment] 2022-05-28 18:52
Hi! I just managed to break the config.yaml on prupose.

Do that by clicking fast on the down/up arrow button that allows the user to change the quantity of ssh sessions that appear in the recent sessions dropdown menu.

I assume that for some reason the file breaks and lost some or all of the useful config data to Tabby.

What i did was to make a script thats backs up for me that config file every 5 minutes. Yes, i know that souns insane but i dont want to ever loose 50 sessions and to have to load them all over again.

In fact i allready test to replace that file with a back up and works just fine.

**Comment by niceit** [comment] 2022-06-04 15:35
Give a try with the sync configs to your clouds, in case your local is lost, restore from the cloud
https://www.npmjs.com/package/terminus-cloud-settings-sync

**Comment by DreamPWJ** [comment] 2022-06-11 14:07
@brunolabozzetta I lost all configuration using the sync that comes with tabby, is there a solution?

**Comment by brunolabozzetta** [comment] 2022-06-12 20:45
@DreamPWJ not one that i'am aware of.

What i did as a "solution" was make a backup script with PHP and backup incrementally that file EVERT FIVE MINUTES.

If it brakes, it's plausible that i may lost some new session of the last five minutes, but not all of my sessions.

This is what worked for me...

**Comment by Eugeny** [comment] 2023-02-04 08:51
Duplicate of #5355

**Closed by Eugeny** 2023-02-04 08:51 UTC
