### ISSUE TITLE
Tabby 1.0.212 on macOS: Application Fails to Launch

### ISSUE THREAD

**Issue by ZheCheng** [Eugeny/tabby#9943] opened 2024-09-18 07:56 UTC
**I am experiencing an issue with Tabby version 1.0.212 on macOS. After updating to this version, the application fails to launch. There are no error messages displayed, and the application does not appear in the Dock or the Applications list. This issue prevents me from using Tabby as expected**:

**To Reproduce**:
1. Ensure that Tabby is updated to version 1.0.212 using the latest release from the Tabby GitHub repository.
2. Launch Tabby on a macOS system.

Additional information:
- macOS Version: [macOS Sonoma 14.7]
- Tabby Version: [tabby-1.0.212-macos-arm64.dmg]

![image](https://github.com/user-attachments/assets/8c821dec-2b32-455d-9026-4c23901650e3)
![image](https://github.com/user-attachments/assets/f57adaee-cadd-44d3-be89-d786968b1734)

**Comment by barseghyanartur** [comment] 2024-09-18 08:07
Same for me. Does not launch. Previous version works OK. I would suggest to start versioning Tabby on brew. Or at least allow installation of `@previous` version.

**Comment by ctyytc** [comment] 2024-09-18 08:22
> **I am experiencing an issue with Tabby version 1.0.212 on macOS. After updating to this version, the application fails to launch. There are no error messages displayed, and the application does not appear in the Dock or the Applications list. This issue prevents me from using Tabby as expected**:
> 
> **To Reproduce**:
> 
> 1. Ensure that Tabby is updated to version 1.0.212 using the latest release from the Tabby GitHub repository.
> 2. Launch Tabby on a macOS system.
> 
> Additional information:
> 
> * macOS Version: [macOS Sonoma 14.7]
> * Tabby Version: [tabby-1.0.212-macos-arm64.dmg]
> 
> ![image](https://private-user-images.githubusercontent.com/18591933/368473235-8c821dec-2b32-455d-9026-4c23901650e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDc5OTYsIm5iZiI6MTcyNjY0NzY5NiwicGF0aCI6Ii8xODU5MTkzMy8zNjg0NzMyMzUtOGM4MjFkZWMtMmIzMi00NTVkLTkwMjYtNGMyMzkwMTY1MGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA4MjEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZDQzMmI2NjJmMzBiNWE4ZmFmN2QwYmQ0MzZhNmJlZTY5MzIwNzUyOGQ2MDU2ODY5OGRkM2VmMGI5Yzk5YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FBsTyJUDcjeOtxvlZfWpAH03gRQgvTrICVHRmgY1d9c) ![image](https://private-user-images.githubusercontent.com/18591933/368473293-f57adaee-cadd-44d3-be89-d786968b1734.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDc5OTYsIm5iZiI6MTcyNjY0NzY5NiwicGF0aCI6Ii8xODU5MTkzMy8zNjg0NzMyOTMtZjU3YWRhZWUtY2FkZC00NGQzLWJlODktZDc4Njk2OGIxNzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA4MjEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZWJkMjMwZDI1ZjU3ODk0M2NjNWQ2MjI5Mzk3ZDliYmFiOGYxNGY2MmMyZDk5NDZiNDExMDBjMTFiZDg5NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e5t80gmSPiJ9Q5ZF0apmJrWrpqJP2FO4Xtryztummnc)

Same to me, on MacOS 15.0

**Comment by bh** [comment] 2024-09-18 09:03
```
$ open /Applications/Tabby.app
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x60000080c210 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
```
macOS 15.1

**Comment by bogdanm** [comment] 2024-09-18 09:07
Probably a duplicate of #9942

**Comment by bh** [comment] 2024-09-18 09:11
Temp. downgrade the version before works fine.

```
$ brew install --cask /tmp/tabby.rb
==> Upgrading 1 outdated package:
tabby 1.0.212 -> 1.0.211
==> Upgrading tabby
==> Downloading https://github.com/Eugeny/tabby/releases/download/v1.0.211/tabby-1.0.211-macos-arm64.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/77213120/16b174dd-6d55-4b3e-9192-c1a68a2c7998?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credent
####################################################################################################################################################################################### 100.0%
==> Backing App 'Tabby.app' up to '/opt/homebrew/Caskroom/tabby/1.0.212/Tabby.app'
==> Removing App '/Applications/Tabby.app'
==> Moving App 'Tabby.app' to '/Applications/Tabby.app'
==> Purging files for version 1.0.212 of Cask tabby
🍺  tabby was successfully upgraded!
```

**Comment by Eugeny** [comment] 2024-09-18 09:33
Fixed in v213

**Closed by Eugeny** 2024-09-18 09:33 UTC
Labels: T: Bug
