### ISSUE TITLE
posix_spawn(3) failed

### ISSUE THREAD

**Issue by Calatrava83** [Eugeny/tabby#4423] opened 2021-08-16 09:34 UTC
Version: 1.0.153
Platform: macOS arm64 20.6.0
Plugins: title-control, theme-windows10, theme-hype, theme-gruvbox, sync-config, scrollbar, save-output, relaxed-theme, quick-cmds
Frontend: xterm

Posix_spawn not working on mac and linux.

**Comment by Eugeny** [comment] 2021-08-16 11:50
Duplicate of #4422

**Closed by Eugeny** 2021-08-16 11:50 UTC
