### ISSUE TITLE
Hang after last update

### ISSUE THREAD

**Issue by maurosrios** [Eugeny/tabby#9794] opened 2024-07-17 14:59 UTC
Version: 1.0.210
Platform: Windows x64 10.0.22631
Plugins: none
Frontend: xterm-webgl

After last update, I open Tabby and don't let me do anything. Options like new terminal, profile, settings, get market, but when i try to opened, don't do anything. I try downgrade the version, but same issue. no response on click

**Comment by Smiie-2** [comment] 2024-07-17 16:04
I have the same. If I run tabby as admin, it works as excpected.

**Comment by maurosrios** [comment] 2024-07-17 16:22
I try as admin, but same issue. I just read other post, where Eugeny recomend downgrade to version alpha 08 and that work for me. Everything is back to normal. For the moment I will avoid upgrade (09-10).

**Comment by theredcmdcraft** [comment] 2024-07-17 21:03
having the same issue. Also run as Admin didn`t work for me.

**Comment by Gyarbij** [comment] 2024-07-18 08:25
Same here with the latest version not allowing input. The running admin also does not work as fix.

Downgrading to [Alpha 208](https://github.com/Eugeny/tabby/releases/tag/v1.0.208)  as suggested by @maurosrios does resolve it for me as a temporary fix.

Merely speculation but do you guys also have an encrypted vault?

Version: 1.0.210
Platform: Windows x64 10.0.22631
Plugins: Alot

**Comment by vecinohk** [comment] 2024-07-18 10:19
Do not update and stay on the version: https://github.com/Eugeny/tabby/releases/tag/v1.0.208 ... The problem was reported here https://github.com/Eugeny/tabby/issues/9787 and apparently everyone with Windows has it.

**Comment by Eugeny** [comment] 2024-07-18 21:47
Duplicate of #9787

**Closed by Eugeny** 2024-07-18 21:47 UTC
