### ISSUE TITLE
Min/Max/Close buttons on hover is not aligned on Windows 10

### ISSUE THREAD

**Issue by Novezeil** [Eugeny/tabby#4932] opened 2021-11-16 03:01 UTC
![tabby_mmc_issue](https://user-images.githubusercontent.com/7578569/141887836-163d8577-f3d1-48c6-a2e2-3265e2173f22.gif)

Environment: Windows 10
Issue only found on Alpha 162

**Comment by Eugeny** [comment] 2021-11-16 10:07
Duplicate of #4926

**Closed by Eugeny** 2021-11-16 10:07 UTC
