### ISSUE TITLE
Can I sort profiles & connections by name？

### ISSUE THREAD

**Issue by ansoda** [Eugeny/tabby#5832] opened 2022-02-25 02:44 UTC
Can I sort profiles & connections by name？

**Comment by EricYangHai** [comment] 2022-03-09 14:31
my ways is rename all profiles with a prefix, the most popular profiles will have prefix "A-", the prefix for  second level profiles is "B-".
hope this can solve your problem

**Comment by ansoda** [comment] 2022-03-17 02:18
Ok,thanks!

**Comment by Eugeny** [comment] 2022-05-26 10:57
Duplicate of #3059

**Closed by Eugeny** 2022-05-26 10:57 UTC
