### ISSUE TITLE
Unexpected Characters on Command Line

### ISSUE THREAD

**Issue by aimmta** [Eugeny/tabby#4859] opened 2021-10-30 12:23 UTC
Version: 1.0.161
Platform: Windows x64 6.1.7601
Plugins: none
Frontend: xterm

When I open tabby and start to type, I get odd characters instead of the typed characters.

![image](https://user-images.githubusercontent.com/63108131/139532720-a6589024-a983-45ea-a978-7b77d30106f0.png)

**Comment by CodeTheMuffin** [comment] 2021-12-19 05:20
I have the same issue :( 
Version 1.0.168
Windows 8.1 64 bit

Plugins: none (what came pre-installed)
Frontend: xterm

Also the color scheme is not working. Only showing one color.
Just installed it today. Was really looking forward to using Tabby :disappointed:

**Comment by AndreKR** [comment] 2022-08-11 22:53
Duplicate of #4372

**Closed** 2022-10-04 19:13 UTC
