### ISSUE TITLE
[Feature Request] Phrase highlighting 

### ISSUE THREAD

**Issue by DanRoses** [Eugeny/tabby#4258] opened 2021-07-23 14:16 UTC
Perhaps in the appearance tab, it would be nice to have a feature where one could add items like words or phrases and choose specific styling attributes to be applied to those strings.  Maybe also with a terminal bell with sound options. # # # #

**Comment by Eugeny** [comment] 2021-07-23 14:18
Duplicate of #632

**Closed by Eugeny** 2021-07-23 14:18 UTC
