### ISSUE TITLE
什么时间可以支持中文？

### ISSUE THREAD

**Issue by China-huc-hk** [Eugeny/tabby#3319] opened 2021-01-11 01:08 UTC
什么时间可以支持中文？

**Comment by not-know** [comment] 2021-02-24 13:45
+1

**Comment by wordhui** [comment] 2021-08-01 09:10
+1
This is the best terminal I have ever used
I also look forward to the menu with Chinese language packs to choose from

**Comment by gexiaosen** [comment] 2021-12-03 08:42
期待支持中文

**Comment by mrxu0** [comment] 2021-12-07 11:24
+1

**Comment by Eugeny** [comment] 2021-12-07 11:46
Duplicate of #2538

**Closed by Eugeny** 2021-12-07 11:46 UTC

**Comment by JuvenileQ** [comment] 2021-12-15 02:15
+1

**Comment by midaug** [comment] 2022-01-04 09:58
+1

**Comment by yuwenhaibo** [comment] 2022-01-19 02:13
+
