### ISSUE TITLE
error on add new profile (ssh) 

### ISSUE THREAD

**Issue by AliKhadivi** [Eugeny/tabby#4356] opened 2021-08-05 15:07 UTC
Version: 1.0.151
Platform: win32 10.0.19042
Plugins: none
----------------------------------
hi ,
I tried to create a new profile and enter all parameters such as host& port& username & password ... 
afer click Save, nothing happens and no profile is created!

**Comment by Eugeny** [comment] 2021-08-05 16:54
Duplicate of #4330

**Closed by Eugeny** 2021-08-05 16:54 UTC
