### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by uicky** [Eugeny/tabby#4412] opened 2021-08-13 05:43 UTC
![问题截图1](https://user-images.githubusercontent.com/48382673/129310529-a205e937-421b-48a4-b494-6933a01a761e.png)
Version: 1.0.152
Platform: win32 10.0.19042
Plugins: elastic-quick-cmds
当使用`clear`命令清屏后，光标移动到了窗体的title下面，用户看不到了

**Comment by livesamarthgupta** [comment] 2021-08-13 08:01
Translation: When the header is pinned and clear command is executed the cursor moves under the title and isn't visible anymore.

**Comment by uicky** [comment] 2021-08-13 08:12
got it thanks

**Comment by Eugeny** [comment] 2021-08-13 12:47
Duplicate of #4384

**Closed by Eugeny** 2021-08-13 12:47 UTC
