### ISSUE TITLE
Tabby Right Click Not Uninstalled After Uninstalling Via add Or Remove Programs

### ISSUE THREAD

**Issue by simyking** [Eugeny/tabby#5361] opened 2022-01-02 10:52 UTC
**Describe the problem**:
[A clear and concise description of what the bug is.]

**To Reproduce**:
[Steps to reproduce the behavior]
I have noticed that if you uninstall Terminus it does not remove the right click shell integration in explorer on windows, the "Paste path into Terminus" option remains as a dead link.

Steps to reproduce:

Install Tabby -setup
Ensure shell integration is enabled (it is by default)
Uninstall Tabby via Add/remove programs
Right click in explorer and the option remains
A workaround is to disable the shell integration in settings prior to uninstalling Tabby
![image](https://user-images.githubusercontent.com/43566899/147873471-dea10401-7ca6-453c-bee4-cf7afd3dd669.png)

**Comment by Eugeny** [comment] 2022-09-04 22:44
Duplicate of #1344

**Closed by Eugeny** 2022-09-04 22:44 UTC
Labels: T: Bug
