### ISSUE TITLE
UI non reactive

### ISSUE THREAD

**Issue by lachnerd** [Eugeny/tabby#9791] opened 2024-07-16 18:10 UTC
Version: 1.0.210
Platform: Windows x64 10.0.22631
Plugins: quick-cmds
Frontend: xterm-webgl

After upgrade to 1.0.210 or 1.0.209 i am unable to click any UI element except github & report a problem, pretty weird

**Comment by vecinohk** [comment] 2024-07-16 18:15
Go back to Alpha 208 and be patient - https://github.com/Eugeny/tabby/issues/9787

**Comment by Eugeny** [comment] 2024-07-18 21:47
Duplicate of #9787

**Closed by Eugeny** 2024-07-18 21:47 UTC
