### ISSUE TITLE
Menu on tab not open

### ISSUE THREAD

**Issue by cedric-r-mycelium** [Eugeny/tabby#9782] opened 2024-07-12 07:50 UTC
Version: 1.0.209
Platform: Windows x64 10.0.22635
Plugins: cloud-settings-sync
Frontend: xterm

Click on menu on tab does not open if double click it's open rename of tab

![image](https://github.com/user-attachments/assets/6d2f83be-0269-4633-879c-e97882bb5cbb)

**Comment by vecinohk** [comment] 2024-07-13 13:43
Looks just like my problem here: https://github.com/Eugeny/tabby/issues/9787 .

**Comment by vecinohk** [comment] 2024-07-14 09:08
@cedric-r-mycelium Try setting "Disable GPU acceleration" - it solved the problem for me.

**Comment by Eugeny** [comment] 2024-07-18 21:47
Duplicate of #9787

**Closed by Eugeny** 2024-07-18 21:47 UTC
