### ISSUE TITLE
Terminal Windows going blank

### ISSUE THREAD

**Issue by ghost** [Eugeny/tabby#8032] opened 2023-03-05 00:55 UTC
Version: 1.0.189
Platform: macOS arm64 22.3.0
Plugins: theme-gruvbox, search-in-browser, quick-restart, fit-screen
Frontend: xterm-webgl

Not sure what's causing this issue.. I've tried recreating it, but it seems to only happen at random. Where when I type, half of the terminal screen will either 'blink' or go black altogether. This also leaks into all of the other terminal tabs I have open. 
When this happens, I have to close all terminal tabs(but not Tabby). Afterwards the issue goes away for a while.

Also. I've only experienced this while in Neovim. But I'm mainly in Neovim while using the terminal anyways.

**Comment by x-lugoo** [comment] 2023-03-09 13:43
I have suffered the same issue.

**Comment by Aldrich814** [comment] 2023-03-18 19:25
I've been trying to recreate this issue. But it seems to only happen at random. I'm going to attach my devtools log and a screenshot of what it looks like when this bug happens.

[TabbyScren.log](https://github.com/Eugeny/tabby/files/11009393/TabbyScren.log)
<img width="1477" alt="Screenshot 2023-03-18 at 3 21 22 PM" src="https://user-images.githubusercontent.com/67401897/226132756-6a816d1c-bbfa-4a42-a0da-c618bd4eefb6.png">

**Comment by saudiqbal** [comment] 2024-03-02 17:56
Same problem here.

**Comment by adam-kosseck** [comment] 2024-07-16 03:05
I'm also experiencing what appears to be the same issue (Windows 11).  It only seems to have started since the most recent update (209?).

Everything is working ok then suddenly the contents of all visible terminal windows go blank.
If I trigger a "split" from the tabby menu they come back.

This happens several times a day.

Happy to provide any information required to help track down the root cause of this issue.

**Comment by Eugeny** [comment] 2024-07-16 07:58
Fixed in 210

**Closed by Eugeny** 2024-07-16 07:58 UTC
