### ISSUE TITLE
Don't work right-click to pase and etc.

### ISSUE THREAD

**Issue by ggfable** [Eugeny/tabby#7246] opened 2022-10-06 16:45 UTC
Version: 1.0.184
Platform: Windows x64 10.0.19043
Plugins: none
Frontend: xterm-webgl

its from start terminal.

![image](https://user-images.githubusercontent.com/55110318/194371112-59eb6314-a4d8-422e-8b2f-883bf664b2c5.png)

**Comment by flyinghail** [comment] 2022-10-16 10:33
Same problem, xterm works fine.

**Comment by Gaibhne** [comment] 2022-10-24 18:49
Duplicate of #7259 I think

**Comment by Eugeny** [comment] 2022-10-27 12:52
Fixed

**Closed by Eugeny** 2022-10-27 12:52 UTC
