### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by pop-lee** [Eugeny/tabby#5499] opened 2022-01-17 03:43 UTC
by password
![image](https://user-images.githubusercontent.com/7325728/149705405-59842b8c-3b8c-46a0-b7c8-dbef6d32dc09.png)

**Comment by pop-lee** [comment] 2022-01-17 03:44
Tabby  Version 1.0.169 (1.0.169)
MacOS 12.0.1

**Comment by wgicio** [comment] 2022-04-05 03:22
I have similar issue

**Comment by uuair** [comment] 2022-05-04 02:01
useing "ssh-keygen -t ed25519" instead rsa

**Comment by utgpay2** [comment] 2022-07-14 06:24
all bro,ubuntu have the problem,use centos is ok

**Comment by Eugeny** [comment] 2022-07-18 20:54
Duplicate of #6804 - see that issue for more info.

**Closed by Eugeny** 2022-07-18 20:54 UTC
Labels: T: Bug
