### ISSUE TITLE
[Feature request] Multi language support

### ISSUE THREAD

**Issue by StormYudi** [Eugeny/tabby#1931] opened 2019-12-30 01:44 UTC
I am a developer from China, and I love this app, but it's in English, I hope it can add multiple language support, we can help to translate.

**Comment by TJ619** [comment] 2020-05-06 17:27
Ready to help for translate in Fr :)

**Comment by cayenne17** [comment] 2020-11-24 21:35
I am willing to help translate into French

**Comment by Paul75** [comment] 2021-05-12 16:41
Hello,

If you want help ....

**Comment by mingzijian** [comment] 2021-07-02 08:01
Multi language support.

> I am a developer from China, and I love this app, but it's in English, I hope it can add multiple language support, we can help to translate.

hope too!

**Comment by mingzijian** [comment] 2021-07-02 08:04
It can be a plugin to support multi language.

**Comment by Eugeny** [comment] 2022-01-08 15:08
Duplicate of #2538

**Closed by Eugeny** 2022-01-08 15:08 UTC
Labels: T: Enhancement
