### ISSUE TITLE
Cannot click in the main window with v .209

### ISSUE THREAD

**Issue by Chrismarsh** [Eugeny/tabby#9775] opened 2024-07-10 17:58 UTC
**Describe the problem**:

I updated to 209 and now clicking in the window (to start a new connection, for example) does nothing.

I deleted the config, and I was able to click through the on-board preference setup. However, after that, click does nothing.

This is on Windows 11

**To Reproduce**:
Version: 1.0.209
Platform: Windows x64 10.0.22631
Plugins: none
Frontend: xterm-webgl

**Comment by Eugeny** [comment] 2024-07-10 19:31
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by Chrismarsh** [comment] 2024-07-11 13:48
Beyond strange. As soon as I launched it with `--inspect` the problem has gone away and has stayed away. I note that I had to use `--inspect`  as `--debug` was flagged as deprecated and wouldn't do launch the program.

**Comment by tomasz2048** [comment] 2024-07-11 15:42
This happens to me too on two different machines: in 1.0.209 I can't open new tab, profiles&connections or config. 
I can switch between tabs that were saved from last session from before 208->209 update.
Starting with --inspect did not help.
Had to revert to 208.

**Comment by Chrismarsh** [comment] 2024-07-11 19:26
Reopened based on @tomasz2048. Does `--inspect` let you debug it as per @Eugeny 's suggestion?

**Comment by tomasz2048** [comment] 2024-07-11 20:40
I'm getting inconsistent behavior, 2 different scenarios [2a and 2b is probably a matter of some random length timing...]: 

1. sometimes can open new tabs/profiles/settings all the time until I close the app 
2a. sometimes can open new tabs/profiles/settings only for a few seconds after app startup, 
2b. sometimes can't open tabs/profiles/settings at all from the start.

I don't see any errors in DevTools console after running with --inspect

I see some errors in CMD from where I run it with --inspect flag:
but those show up even in scenario when I can open new tabs permanently during app run

PS C:\dev> C:\Users\tomas\AppData\Local\Programs\Tabby\Tabby.exe --inspect
PS C:\dev>
Debugger listening on ws://127.0.0.1:9229/e3c36656-7834-4c7b-92e7-4ab050465ff4
For help, see: https://nodejs.org/en/docs/inspector
[Glasstron/DWM] Trying to load the native module...
[Glasstron/DWM] Native module loaded
(node:90280) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Tabby --trace-deprecation ...` to show where the warning was created)
Checking for update
Update for version 1.0.209 is not available (latest version: 1.0.209, downgrade is disallowed).
[88384:0711/153326.615:ERROR:jump_list.cc(300)] Failed to append custom category 'Recent' to Jump List due to system privacy settings.
[88384:0711/153326.647:ERROR:jump_list.cc(300)] Failed to append custom category 'Profiles' to Jump List due to system privacy settings.

**Comment by JamesDBartlett3** [comment] 2024-07-11 23:26
I just upgraded to Tabby v1.0.209 today, and I started experiencing this same bug immediately after the upgrade. 

If I launch Tabby with the `--inspect` argument, it will start up normally and open a new PowerShell tab, but only about ⅓ of the time. The other ⅔ of the time, it just hangs on this screen:
![image](https://github.com/user-attachments/assets/c2efcf75-fab4-4976-8794-6ccb4fcd2479)
I can click on the buttons, and they do their little "I've been clicked!" animation, but nothing else happens. The only buttons that actually work are minimize, maximize, and close. I can also show/hide the window using the "Toggle terminal window" hotkey, but that's not very useful if the rest of the app is frozen. 😜

**Comment by GuangDai** [comment] 2024-07-12 04:55
> I just upgraded to Tabby v1.0.209 today, and I started experiencing this same bug immediately after the upgrade.
> 
> If I launch Tabby with the `--inspect` argument, it will start up normally and open a new PowerShell tab, but only about ⅓ of the time. The other ⅔ of the time, it just hangs on this screen:如果我用 `--inspect` 参数启动 Tabby,它将正常启动并打开一个新的 PowerShell 选项卡,但只有大约 ⅓ 的时间。其余 ⅔ 的时间,它只是在此屏幕上挂起: ![image](https://private-user-images.githubusercontent.com/37491308/348021254-c2efcf75-fab4-4976-8794-6ccb4fcd2479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NjAzNjQsIm5iZiI6MTcyMDc2MDA2NCwicGF0aCI6Ii8zNzQ5MTMwOC8zNDgwMjEyNTQtYzJlZmNmNzUtZmFiNC00OTc2LTg3OTQtNmNjYjRmY2QyNDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA0NTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYzg3MTJiNDdjNWUyYjI4OWE1OGM4NjdlMDk5MmFjNzMyNTQxY2QxMGY1NjQ3MTY1Njc4ZGQwOGM2NjNkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NcdX-LB_hiJkDYyXjl9X6agJgFEwG4cmeJtZ8ZQvHAQ) I can click on the buttons, and they do their little "I've been clicked!" animation, but nothing else happens. The only buttons that actually work are minimize, maximize, and close. I can also show/hide the window using the "Toggle terminal window" hotkey, but that's not very useful if the rest of the app is frozen. 😜我可以点击按钮,它们会做它们的小"我被点击了!"动画,但没有其他事情发生。唯一真正有效的按钮是最小化、最大化和关闭。我也可以使用"切换终端窗口"热键来显示/隐藏窗口,但如果应用程序的其余部分都被冻结,这并不太有用。😜

Same. I am using Archlinux KDE. Maybe arch is too new?

**Comment by fgpetter** [comment] 2024-07-14 15:48
Same problem here, it seems that process wont end when you close the window. When I tried to uninstall (windows), it shows a message that Tabby is active and I have to close before uninstall. I had to reboot and uninstal to rollback to 208.

**Comment by Eugeny** [comment] 2024-07-18 21:58
Duplicate of #9787

**Closed by Eugeny** 2024-07-18 21:58 UTC
Labels: T: Bug
