### ISSUE TITLE
Whether SFTP is enabled to directly access the current ssh directory.Xshell software is ok.Shell-working-directory-reporting is not valid

### ISSUE THREAD

**Issue by zxiaozhou** [Eugeny/tabby#5230] opened 2021-12-20 09:43 UTC
**Describe the solution you'd like**
1. Whether SFTP is enabled to directly access the current ssh directory.Xshell software is ok,This facilitates uploading files to the current SSH directory
2. Xshell software video demonstration
https://user-images.githubusercontent.com/62740686/146743801-a9ac33bc-1dc9-4817-8cbb-16b8f409e383.mp4

## Shell-working-directory-reporting is not valid
![image](https://user-images.githubusercontent.com/62740686/146745608-853c57a4-e66f-4636-899b-c81acc6bed6f.png)
![image](https://user-images.githubusercontent.com/62740686/146745715-2e45fbef-be39-4ec2-84f1-bbc42729b39b.png)

**Comment by Eugeny** [comment] 2021-12-20 09:47
Duplicate of #5229

**Closed by Eugeny** 2021-12-20 09:47 UTC
