### ISSUE TITLE
Feature: SSH connection multiplexing

### ISSUE THREAD

**Issue by RichardLS09** [Eugeny/tabby#5134] opened 2021-12-13 03:13 UTC
I want to run "ssh -o ControlMaster=auto -o ControlPath=/save/path host:port" using tabby.
But, i don't know how to add ssh options.
Need help,please!

**Comment by Eugeny** [comment] 2021-12-13 10:29
Tabby doesn't support connection multiplexing yet.

**Comment by jzuhone** [comment] 2021-12-21 03:46
would love this feature.

**Comment by Eugeny** [comment] 2021-12-21 22:30
Duplicate of #4795

**Closed by Eugeny** 2021-12-21 22:30 UTC
Labels: T: Enhancement, Plugin: SSH
