### ISSUE TITLE
Option to set line-height for the text rendered in the terminal

### ISSUE THREAD

**Issue by vivekragunathan** [Eugeny/tabby#5194] opened 2021-12-17 00:29 UTC
Would be great to have a way to set line height (vertical height) and character spacing width. The text looks a bit cramped for almost any font I tried.

I was not able to find a way using `Appearance -> Custom CSS` to change the line height of the text rendered in the terminal. 

<img width="893" alt="CleanShot 2021-12-16 at 16 29 59@2x" src="https://user-images.githubusercontent.com/292160/146468829-5e619971-01b0-4bda-ab6c-5602d367d22d.png">
vs 

Demo in settings

<img width="1439" alt="CleanShot 2021-12-16 at 16 27 44@2x" src="https://user-images.githubusercontent.com/292160/146468687-0d0fa2f6-d9e5-4a2e-a4b5-aef60d9b9a0d.png">

**Comment by Eugeny** [comment] 2021-12-17 10:10
Duplicate of #141

**Closed by Eugeny** 2021-12-17 10:10 UTC
