### ISSUE TITLE
feature request: test connection button

### ISSUE THREAD

**Issue by h3n4l** [Eugeny/tabby#6485] opened 2022-05-23 08:22 UTC
**Is your feature request related to a problem? Please describe.**
Noop.

Tabby is a good terminal! When I add a profile in Tabby, I really want to test it is whether correct or not. So do you have plans to support adding a test connection button? For example, in Navicat:
<img width="953" alt="CleanShot 2022-05-23 at 16 19 00@2x" src="https://user-images.githubusercontent.com/87714218/169775592-b4068779-c38c-4c06-a06c-167230aa87ef.png">
There is a `Test Connection` in the lower left corner.
If it isn't on your roadmap, I can try to add it by myself, but it may take a while, I'm a beginner at TypeScript : ).

**Comment by Eugeny** [comment] 2022-05-23 14:03
Duplicate of #6370

**Closed by Eugeny** 2022-05-23 14:03 UTC
