### ISSUE TITLE
"@" and "|" not working 

### ISSUE THREAD

**Issue by Peachy74** [Eugeny/tabby#9779] opened 2024-07-11 09:33 UTC
tabby terminal 1.0.209 on macos
option+l should normally be the @.
I get an ls - directory listing.
In an alternative terminal option+l (@) or option+7 (|) works.
A hotkey is also not set up.
does anyone have an idea?
Kind regards

**Comment by Peachy74** [comment] 2024-07-11 10:34
No problem with tabby 1.0.207

**Comment by pebosi** [comment] 2024-07-12 06:13
Same problem on mac os sonoma, problem was already on 1.0.208

**Comment by bh** [comment] 2024-07-12 08:27
Duplicate of #9746

**Closed** 2024-07-15 21:29 UTC
Labels: T: Bug
