### ISSUE TITLE
Are you considering adding highlight words support?

### ISSUE THREAD

**Issue by lucas-law** [Eugeny/tabby#5350] opened 2021-12-31 11:43 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use the terminal to view some keywords, I hope these words can be highlighted

**Describe the solution you'd like**
Add a plug-in to support terminal keyword highlighting

**Describe alternatives you've considered**
Like xhell 7， it can highlight words
Thank you

**Comment by lucas-law** [comment] 2021-12-31 11:44
My friends and I, even my colleagues in the company, are using tabby a lot, but the lack of this highlighting function makes us very troubled.

**Comment by DanRoses** [comment] 2022-01-04 14:53
Very unlikely. 
https://github.com/Eugeny/tabby/issues/632#issuecomment-1002938290

**Comment by Qiming-Liu** [comment] 2022-01-19 02:52
Duplicate of #632

**Comment by lucas-law** [comment] 2022-12-09 09:58
Duplicate

**Closed** 2022-12-09 09:58 UTC
