### ISSUE TITLE
How to display IP in ssh tag？，instead of showing hostname 

### ISSUE THREAD

**Issue by EliLiu-YF** [Eugeny/tabby#6069] opened 2022-04-01 06:46 UTC
![image](https://user-images.githubusercontent.com/69829859/161210084-cd95631b-c6fc-4388-a5af-f017aa6e3db2.png)

**Comment by Eugeny** [comment] 2022-04-01 06:59
Duplicate of #3085

**Closed by Eugeny** 2022-04-01 06:59 UTC
