### ISSUE TITLE
Every time I use SFTP and want to view recent files, it takes a lot of time to drag the slider to the very bottom.

### ISSUE THREAD

**Issue by goophps** [Eugeny/tabby#5741] opened 2022-02-13 11:57 UTC
Every time I use SFTP to view recent files, I have to drag the slider to the bottom for a long time. I hope this can be optimized.

**Comment by goophps** [comment] 2022-02-16 18:50
anyone there?

**Comment by goophps** [comment] 2022-02-17 07:35
no one cares about me

**Comment by goophps** [comment] 2022-03-23 05:45
Come on people, how come no one pays attention to this demand!

**Comment by Eugeny** [comment] 2022-03-23 08:04
Duplicate of #4180

**Closed by Eugeny** 2022-03-23 08:04 UTC
