### ISSUE TITLE
Not support other encodings

### ISSUE THREAD

**Issue by tzzs** [Eugeny/tabby#5290] opened 2021-12-24 08:42 UTC
**Describe the problem**:
[A clear and concise description of what the bug is.]
This app is very useful and fancy, but which is only supports utf8 encoding. Others such as GBK and IBM* are not support.

**To Reproduce**:
[Steps to reproduce the behavior]
Only need to connect to a non-utf8 encoded server via SSH.

**Comment by Eugeny** [comment] 2022-05-17 06:10
Duplicate of #2995

**Closed by Eugeny** 2022-05-17 06:10 UTC
Labels: T: Bug
