### ISSUE TITLE
Context menu does not open on right-click

### ISSUE THREAD

**Issue by mullerch** [Eugeny/tabby#7359] opened 2022-10-24 07:58 UTC
Since 184, right click on a pane does not show the context menu anymore.

Context menu can be opened through the tab `...` button. However, this does not fit all use cases, e.g. when there are multiple panes in a tab.

Version: 1.0.184
Platform: Linux x64 5.19.0-23-generic
Plugins: none
Frontend: xterm-webgl

**Comment by Gaibhne** [comment] 2022-10-24 18:49
Duplicate of #7259 I think

**Comment by Eugeny** [comment] 2022-10-27 12:52
Fixed

**Closed by Eugeny** 2022-10-27 12:52 UTC
