### ISSUE TITLE
Can SFTP support uploading folders?

### ISSUE THREAD

**Issue by vcqr** [Eugeny/tabby#6806] opened 2022-07-19 02:35 UTC
**Is your feature request related to a problem? Please describe.**

To upload files in multiple directories, you need to open the folder several times to select the file

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Eugeny** [comment] 2022-07-31 16:32
Duplicate of #4946

**Closed by Eugeny** 2022-07-31 16:32 UTC
