### ISSUE TITLE
Is it possible to customize sorting groups and ssh connections under specific groups？

### ISSUE THREAD

**Issue by DreamPWJ** [Eugeny/tabby#6498] opened 2022-05-26 03:40 UTC
![image](https://user-images.githubusercontent.com/16730031/170411332-94dca846-8ff6-4e9f-a8d3-51c71c4ab5a4.png)  Prioritization makes it easier for us to find

**Comment by Eugeny** [comment] 2022-05-26 10:57
Duplicate of #3059

**Closed by Eugeny** 2022-05-26 10:57 UTC
