### ISSUE TITLE
Logging in with the wrong private key with password will lose all the configuration files and can reproduce the error

### ISSUE THREAD

**Issue by jojodestiny** [Eugeny/tabby#7633] opened 2022-12-09 10:59 UTC
Version: 1.0.187
Platform:Windows11 x64 21h2
Plugins: none
Frontend: xterm-webgl
All my configurations are gone because I chose the wrong private key

1.Everything is set by default but I have set the vault.

2.When I was adding an ssh connection, I chose the wrong private key, then I followed the instructions and entered the password twice, the password of the private key was correct but not the secret key of the current ssh connection, then all the configuration was lost.

3.I found the problem and ran a repeat test, and each time.

Okay, let's reproduce the problem.
1. First select an incorrect private key with a password 
   This private key does not belong to the current ssh connection
![image](https://user-images.githubusercontent.com/21281503/206685312-868c0604-1506-418e-9a6c-40915ab7318f.png)

2. Next, start connecting to ssh 
3.Enter the correct private key password
![image](https://user-images.githubusercontent.com/21281503/206686139-c2fe730e-3825-47d8-a9da-4c6d68654ffc.png)
Accept and remember  key

![image](https://user-images.githubusercontent.com/21281503/206686303-080905fe-e8ac-446f-8872-7e102c3816eb.png)
Enter the password again
![image](https://user-images.githubusercontent.com/21281503/206686603-b58909bb-5e7c-4598-a8d2-c9ff3f650eb0.png)
Accept and remember  key again

![image](https://user-images.githubusercontent.com/21281503/206686805-d90395f8-ed10-4acc-a250-5b097de3b287.png)

It is finished here!
All configurations have disappeared including shortcuts
![image](https://user-images.githubusercontent.com/21281503/206687008-d456d34f-e57c-4f17-a5c5-62323731d41a.png)
Hope to solve this problem 
Thanks!
Video Demo

https://user-images.githubusercontent.com/21281503/206726523-8517fa69-b7dc-4046-a076-8e257b138036.mp4

**Comment by jojodestiny** [comment] 2022-12-09 11:52
Sorry, I didn't find this error on my other computer. I tried to find the common denominator to trigger this error.

**Comment by jojodestiny** [comment] 2022-12-09 12:50
I turned off the Encrypt config file and the problem does not occur 

But I don't see it every time on the other computer, probably because there is an early terminus

**Comment by aliaspablo** [comment] 2023-01-04 18:24
I have the same Problem, i lost all my config Files.

**Comment by fjacobi** [comment] 2023-01-19 07:43
I ran into this problem yesterday and was devastated - until I manually installed tabby and did not use the scoop installation and all data was restored.

**Comment by floid1986** [comment] 2023-01-26 10:47
@fjacobi Hello, I also ran into this problem. How can I fix this ? I've lost all my connections in 5 years =(

**Comment by fjacobi** [comment] 2023-01-26 11:05
@floid1986 I just installed the client manually and everything was back. Didn't do anything else, perhaps I was just lucky.

To me it seems a problem with the persisting data of a scoop installation, i.e. folder links.

**Comment by Eugeny** [comment] 2023-01-29 12:31
Has everbody else having this problem installed Tabby from scoop as well?

**Comment by Eugeny** [comment] 2023-02-04 08:51
Duplicate of #5355 - check it out for a possible fix

**Closed by Eugeny** 2023-02-04 08:51 UTC
Labels: T: Bug
