### ISSUE TITLE
Still can’t type ~ using ergonomic "bépo" layout on macOS

### ISSUE THREAD

**Issue by JLTastet** [Eugeny/tabby#9748] opened 2024-06-28 14:47 UTC
Using `tabby-1.0.208-macos-arm64.dmg` on macOS 14.5 (23F79) with the ergonomic "bépo" layout (French Dvorak), I cannot type the character `~` (usually entered using the combination ⌥+K). Instead, a backtick \` is printed. This makes the terminal unusable, since this character is used so broadly. This only happens with tabby, not with other apps.

EDIT: additionally, typing `_` using ⌥+Space prints `-` instead, and using ⌥ with the numeric row prints the number instead of the corresponding "AltGR" character.

This is very reminiscent of the following (solved) issues, suggesting that the underlying issue is still present:
- https://github.com/Eugeny/tabby/issues/5005
- https://github.com/Eugeny/tabby/issues/4458
- https://github.com/Eugeny/tabby/issues/4433
- https://github.com/Eugeny/tabby/issues/4006
- https://github.com/Eugeny/tabby/issues/3324
- https://github.com/Eugeny/tabby/issues/2866
- https://github.com/Eugeny/tabby/issues/1373
- https://github.com/Eugeny/tabby/issues/768

Below is the keyboard layout, so you don’t have to look it up.

Top level:
<img width="602" alt="image" src="https://github.com/Eugeny/tabby/assets/8004066/a8293f32-c1c7-4965-9ab5-8b9c01d6300c">

With ⌥ (left or right) pressed:
<img width="602" alt="image" src="https://github.com/Eugeny/tabby/assets/8004066/8412f36a-4f86-4325-a576-e0381df9820a">

The locale is `en_US.UTF-8`.

Let me know if you need any additional information!

**Comment by bh** [comment] 2024-07-01 08:10
Duplicate of #9746?

**Comment by JLTastet** [comment] 2024-07-01 20:04
Indeed, this seems to be a regression!

I just downgraded to 1.0.207, and I can now type the offending characters normally.

**Comment by bh** [comment] 2024-07-02 12:48
FYI MacOS Downgrade
```
wget https://raw.githubusercontent.com/Homebrew/homebrew-cask/484891b6f9341536d5b0527bb5e465b130aecb1c/Casks/t/tabby.rb
brew install --cask tabby.rb
```

**Closed** 2024-07-15 21:29 UTC
Labels: T: Bug
