### ISSUE TITLE
How to configure the language

### ISSUE THREAD

**Issue by slatonwu** [Eugeny/tabby#4640] opened 2021-09-23 05:54 UTC
How to configure the language?

**Comment by psyuhen** [comment] 2021-09-23 08:13
不知道哪里配置的

**Comment by Jonnyan404** [comment] 2021-09-23 12:09
暂时不支持,估计得等等了...

**Comment by slatonwu** [comment] 2021-09-24 06:52
The software itself should be internationalized。

![image](https://user-images.githubusercontent.com/9948988/134631014-8fb407d9-6ad5-4bc7-99bf-395ede46e1cd.png)

**Comment by ydcool** [comment] 2021-09-24 08:30
> The software itself should be internationalized。
> 
> ![image](https://user-images.githubusercontent.com/9948988/134631014-8fb407d9-6ad5-4bc7-99bf-395ede46e1cd.png)

I think those language files are from the Electron...

**Comment by Eugeny** [comment] 2021-12-06 08:15
Duplicate of #2538

**Closed by Eugeny** 2021-12-06 08:15 UTC
