### ISSUE TITLE
When install tabby on Ubuntu 24.04

### ISSUE THREAD

**Issue by ZonghuiWang** [Eugeny/tabby#9605] opened 2024-04-29 02:54 UTC
**Describe the problem**:
need install package gconf2, but no matched version

**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by Upellift99** [comment] 2024-04-29 10:46
Hello, a quick fix while waiting for a real resolution:
```
cd /tmp
mkdir tabby-modify
dpkg-deb -x tabby-1.0.207-linux-x64.deb tabby-modify
dpkg-deb -e tabby-1.0.207-linux-x64.deb tabby-modify/DEBIAN
vi tabby-modify/DEBIAN/control
```
remove dependencies to gconf2 and gconf-service
```
dpkg-deb -b tabby-modify tabby-modified.deb
dpkg -i tabby-modified.deb
```

**Comment by theofficialgman** [comment] 2024-05-09 15:44
duplicate of https://github.com/Eugeny/tabby/issues/9587

**Comment by WyoMurf** [comment] 2024-05-18 16:45
I'm trying to install tabby on kubuntu 24.04; I just tried Upellift99's temp fix, but get this:

sudo dpkg -i tabby-modified.deb 
Selecting previously unselected package tabby-terminal.
(Reading database ... 230637 files and directories currently installed.)
Preparing to unpack tabby-modified.deb ...
Unpacking tabby-terminal (1.0.207) ...
dpkg: dependency problems prevent configuration of tabby-terminal:
 tabby-terminal depends on gnome-keyring; however:
  Package gnome-keyring is not installed.

dpkg: error processing package tabby-terminal (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 tabby-terminal


murf@parse4:/tmp$ sudo apt install gnome-keyring
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 gnome-keyring : Depends: libgck-1-0 (>= 3.3.90) but it is not going to be installed
                 Depends: libgcr-base-3-1 (>= 3.28.0) but it is not going to be installed
                 Depends: gcr (>= 3.4) but it is not going to be installed
                 Depends: p11-kit (>= 0.16) but it is not going to be installed
                 Depends: pinentry-gnome3
                 Recommends: libpam-gnome-keyring but it is not going to be installed
                 Recommends: gnome-keyring-pkcs11 but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

murf@parse4:/tmp$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  gcr gcr4 gnome-keyring gnome-keyring-pkcs11 libgck-1-0 libgck-2-2 libgcr-4-4 libgcr-base-3-1 libgcr-ui-3-1
  libpam-gnome-keyring p11-kit p11-kit-modules pinentry-gnome3
Suggested packages:
  pinentry-doc
The following NEW packages will be installed:
  gcr gcr4 gnome-keyring gnome-keyring-pkcs11 libgck-1-0 libgck-2-2 libgcr-4-4 libgcr-base-3-1 libgcr-ui-3-1
  libpam-gnome-keyring p11-kit p11-kit-modules pinentry-gnome3
0 upgraded, 13 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 1,972 kB of archives.
After this operation, 8,689 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libgck-1-0 amd64 3.41.2-1build3 [79.9 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libgcr-base-3-1 amd64 3.41.2-1build3 [202 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libgck-2-2 amd64 4.2.0-5 [77.0 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libgcr-4-4 amd64 4.2.0-5 [192 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu noble/main amd64 gcr4 amd64 4.2.0-5 [42.9 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libgcr-ui-3-1 amd64 3.41.2-1build3 [124 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu noble/main amd64 gcr amd64 3.41.2-1build3 [60.4 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu noble/main amd64 p11-kit-modules amd64 0.25.3-4ubuntu2 [329 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu noble/main amd64 p11-kit amd64 0.25.3-4ubuntu2 [141 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu noble/main amd64 pinentry-gnome3 amd64 1.2.1-3ubuntu5 [38.3 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu noble/main amd64 gnome-keyring amd64 46.1-2build1 [639 kB]
Get:12 http://us.archive.ubuntu.com/ubuntu noble/main amd64 gnome-keyring-pkcs11 amd64 46.1-2build1 [27.9 kB]
Get:13 http://us.archive.ubuntu.com/ubuntu noble/main amd64 libpam-gnome-keyring amd64 46.1-2build1 [17.4 kB]
Fetched 1,972 kB in 2s (860 kB/s)                
Selecting previously unselected package libgck-1-0:amd64.
(Reading database ... 232637 files and directories currently installed.)
Preparing to unpack .../00-libgck-1-0_3.41.2-1build3_amd64.deb ...
Unpacking libgck-1-0:amd64 (3.41.2-1build3) ...
Selecting previously unselected package libgcr-base-3-1:amd64.
Preparing to unpack .../01-libgcr-base-3-1_3.41.2-1build3_amd64.deb ...
Unpacking libgcr-base-3-1:amd64 (3.41.2-1build3) ...
Selecting previously unselected package libgck-2-2:amd64.
Preparing to unpack .../02-libgck-2-2_4.2.0-5_amd64.deb ...
Unpacking libgck-2-2:amd64 (4.2.0-5) ...
Selecting previously unselected package libgcr-4-4:amd64.
Preparing to unpack .../03-libgcr-4-4_4.2.0-5_amd64.deb ...
Unpacking libgcr-4-4:amd64 (4.2.0-5) ...
Selecting previously unselected package gcr4.
Preparing to unpack .../04-gcr4_4.2.0-5_amd64.deb ...
Unpacking gcr4 (4.2.0-5) ...
Selecting previously unselected package libgcr-ui-3-1:amd64.
Preparing to unpack .../05-libgcr-ui-3-1_3.41.2-1build3_amd64.deb ...
Unpacking libgcr-ui-3-1:amd64 (3.41.2-1build3) ...
Selecting previously unselected package gcr.
Preparing to unpack .../06-gcr_3.41.2-1build3_amd64.deb ...
Unpacking gcr (3.41.2-1build3) ...
Selecting previously unselected package p11-kit-modules:amd64.
Preparing to unpack .../07-p11-kit-modules_0.25.3-4ubuntu2_amd64.deb ...
Unpacking p11-kit-modules:amd64 (0.25.3-4ubuntu2) ...
Selecting previously unselected package p11-kit.
Preparing to unpack .../08-p11-kit_0.25.3-4ubuntu2_amd64.deb ...
Unpacking p11-kit (0.25.3-4ubuntu2) ...
Selecting previously unselected package pinentry-gnome3.
Preparing to unpack .../09-pinentry-gnome3_1.2.1-3ubuntu5_amd64.deb ...
Unpacking pinentry-gnome3 (1.2.1-3ubuntu5) ...
Selecting previously unselected package gnome-keyring.
Preparing to unpack .../10-gnome-keyring_46.1-2build1_amd64.deb ...
Unpacking gnome-keyring (46.1-2build1) ...
Selecting previously unselected package gnome-keyring-pkcs11:amd64.
Preparing to unpack .../11-gnome-keyring-pkcs11_46.1-2build1_amd64.deb ...
Unpacking gnome-keyring-pkcs11:amd64 (46.1-2build1) ...
Selecting previously unselected package libpam-gnome-keyring:amd64.
Preparing to unpack .../12-libpam-gnome-keyring_46.1-2build1_amd64.deb ...
Unpacking libpam-gnome-keyring:amd64 (46.1-2build1) ...
Setting up libgck-2-2:amd64 (4.2.0-5) ...
Setting up libgcr-4-4:amd64 (4.2.0-5) ...
Setting up p11-kit-modules:amd64 (0.25.3-4ubuntu2) ...
Setting up gnome-keyring-pkcs11:amd64 (46.1-2build1) ...
Setting up p11-kit (0.25.3-4ubuntu2) ...
Setting up libgck-1-0:amd64 (3.41.2-1build3) ...
Setting up libgcr-base-3-1:amd64 (3.41.2-1build3) ...
Setting up libpam-gnome-keyring:amd64 (46.1-2build1) ...
Setting up libgcr-ui-3-1:amd64 (3.41.2-1build3) ...
Setting up gcr (3.41.2-1build3) ...
Processing triggers for libglib2.0-0t64:amd64 (2.80.0-6ubuntu3.1) ...
Setting up pinentry-gnome3 (1.2.1-3ubuntu5) ...
Processing triggers for shared-mime-info (2.4-4) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Setting up gnome-keyring (46.1-2build1) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/gnome-keyring-daemon.service → /usr/lib/systemd/user/gnome-keyring-daemon.service.
Created symlink /etc/systemd/user/sockets.target.wants/gnome-keyring-daemon.socket → /usr/lib/systemd/user/gnome-keyring-daemon.socket.
Setting up gcr4 (4.2.0-5) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/gcr-ssh-agent.service → /usr/lib/systemd/user/gcr-ssh-agent.service.
Created symlink /etc/systemd/user/sockets.target.wants/gcr-ssh-agent.socket → /usr/lib/systemd/user/gcr-ssh-agent.socket.
Processing triggers for libc-bin (2.39-0ubuntu8.1) ...
Processing triggers for man-db (2.12.0-4build2) ...
Setting up tabby-terminal (1.0.207) ...

Success!

(just in case other 24.04 people get the same problems.)

**Comment by 120dev** [comment] 2024-06-02 15:53
thats work for me :)))
https://www.youtube.com/watch?v=Ve7g28nd1pY

**Comment by netKoji** [comment] 2024-06-06 15:56
> Hello, a quick fix while waiting for a real resolution:
> 
> ```
> cd /tmp
> mkdir tabby-modify
> dpkg-deb -x tabby-1.0.207-linux-x64.deb tabby-modify
> dpkg-deb -e tabby-1.0.207-linux-x64.deb tabby-modify/DEBIAN
> vi tabby-modify/DEBIAN/control
> ```
> 
> remove dependencies to gconf2 and gconf-service
> 
> ```
> dpkg-deb -b tabby-modify tabby-modified.deb
> dpkg -i tabby-modified.deb
> ```

Thx uuuu so much !!

**Comment by Eugeny** [comment] 2024-06-22 21:26
Fixed in the latest release

**Closed by Eugeny** 2024-06-22 21:26 UTC
Labels: T: Bug
