### ISSUE TITLE
Add a function to download and upload folders

### ISSUE THREAD

**Issue by alfred-hong** [Eugeny/tabby#6002] opened 2022-03-24 02:49 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alfred-hong** [comment] 2022-03-24 02:50
Now there is only the function of uploading and downloading files. I want to add a function of uploading and downloading folders.I hope the author will consider it.

**Comment by Eugeny** [comment] 2022-03-24 08:21
Duplicate of #4946

**Closed by Eugeny** 2022-03-24 08:21 UTC
