### ISSUE TITLE
The saved connections are not shown after upgrade from 1.0.208 to 1.0.209

### ISSUE THREAD

**Issue by TrakerBG** [Eugeny/tabby#9778] opened 2024-07-11 06:24 UTC
Version: 1.0.209
Platform: Windows x64 10.0.22631
Plugins: theme-windows10, theme-hype, save-output, docker
Frontend: xterm-webgl

Hi, the saved profiles are not shown after the upgrade, + sign calling the default connection also isn't working.
Re-installing back 1.0.208 is fine, all is there (not lost).

**Comment by Eugeny** [comment] 2024-07-11 10:18
Please capture DevTools console logs at the time of the issue: https://github.com/Eugeny/terminus/wiki/Debug-logs

**Comment by Matrix777** [comment] 2024-07-12 03:52
same

**Comment by eallion** [comment] 2024-07-12 03:54
same

**Comment by eallion** [comment] 2024-07-12 03:56
![PixPin_2024-07-12_11-55-53](https://github.com/user-attachments/assets/842336b4-080d-46e5-89bd-f3efb1d1648d)

**Comment by chief-lewus** [comment] 2024-07-13 03:06
Same issue here as well

**Comment by Eugeny** [comment] 2024-07-18 21:58
Duplicate of #9787

**Closed by Eugeny** 2024-07-18 21:58 UTC
