### ISSUE TITLE
Tabby is running in task manager, but there is no visible console window 

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [Eugeny/tabby#4296] opened 2021-07-29 18:07 UTC
Tabby was installed successfully - Profile all users.

On the first run, it worked.

On the restart, I see not terminal windows.

I can see 4 tabby processes running, but no visible window has come up.

Windows Server 2012

![image](https://user-images.githubusercontent.com/1735005/127543439-982b426c-e433-4298-b8ce-0f078f4d0f74.png)

**Comment by Eugeny** [comment] 2021-07-29 18:33
Duplicate of #4296

**Closed by Eugeny** 2021-07-29 18:33 UTC

**Comment by CharlesOkwuagwu** [comment] 2021-07-29 18:35
> Duplicate of #4296

Please which duplicate?

**Comment by Eugeny** [comment] 2021-07-29 18:36
This issue is the same as the issue #4296 <- click here to view that issue

**Comment by Eugeny** [comment] 2021-07-29 18:37
My bad, it's #4293
