### ISSUE TITLE
tabby how to set terminal encoding to gbk

### ISSUE THREAD

**Issue by skyou927** [Eugeny/tabby#6127] opened 2022-04-11 03:57 UTC
Version: 1.0.174
Platform: Windows x64 10.0.19044
Plugins: docker
Frontend: xterm

tabby how to set terminal encoding to gbk？

**Comment by skyou927** [comment] 2022-04-11 03:59
tabby how to set terminal encoding to gbk？

**Comment by Eugeny** [comment] 2022-05-17 06:11
Duplicate of #2995

**Closed by Eugeny** 2022-05-17 06:11 UTC
