### ISSUE TITLE
How can I send a command to all active tables?

### ISSUE THREAD

**Issue by Syehunter** [Eugeny/tabby#5863] opened 2022-03-02 14:43 UTC
Windows@1.0.173

I've seen the answer in issue#5822 but it doesn't work.

Is "ctrl-shift-i(pane-focus-all)  -> ls(command) ->  press[enter]"  in the right order?

**Comment by Eugeny** [comment] 2022-03-02 19:02
Yes, but just to clarify: it focuses all _panes_, not _tabs_. For multiple tabs, in the latest release, you can merge them together first (merge-tabs hotkey), then focus-all-panes, and later split them into separate tabs again with the explode-tab hotkey.

**Comment by Eugeny** [comment] 2022-11-01 16:18
Duplicate of #5193

**Closed by Eugeny** 2022-11-01 16:18 UTC
Labels: T: Bug
