### ISSUE TITLE
Shortcut for "scroll terminal to the top"

### ISSUE THREAD

**Issue by konstantin83** [Eugeny/tabby#6155] opened 2022-04-13 10:37 UTC
Hi! Thank you for a wonderfull and really helpfull software. I am relatively new to Ubuntu, and migrated from iTerm2 on MacOS. And Tabby perfectly matched for me. I even think to move to it on my Mac also.

My question is about terminal navigation.

SHIFT+PageUp and SHIFT+PageDown works fine to scroll by a page.

I also binded SHIFT+End to scroll to bottom. But actually any key drops you to bottom, so it is not really nececcary.

What's really missing is shortcut to scroll all the way UP. I didn't find such a shortcut. Maybe you could help telling the shortcut for this action?

**Comment by Eugeny** [comment] 2022-07-26 16:49
Duplicate of #194

**Closed by Eugeny** 2022-07-26 16:49 UTC
Labels: T: Enhancement
