### ISSUE TITLE
Words written on clink terminal is showing unknown characters

### ISSUE THREAD

**Issue by samuelirwin** [Eugeny/tabby#4464] opened 2021-08-22 20:04 UTC
![image](https://user-images.githubusercontent.com/7158166/130368485-a10a8edb-a661-4869-bb88-ba92a821016d.png)

Version: 1.0.155
Platform: Windows x64 6.1.7601
Plugins: clickable-links
Frontend: xterm

**Comment by Eugeny** [comment] 2021-08-23 06:57
Duplicate of #4372

**Closed by Eugeny** 2021-08-23 06:57 UTC
