### ISSUE TITLE
update Tabby new version, all ssh connect config disappear

### ISSUE THREAD

**Issue by itgoyo** [Eugeny/tabby#7782] opened 2023-01-12 06:38 UTC
**Describe the problem**:

MacOS ：big sur 11.6
version 1.0.164->1.0.188
all my mac ssh connect files disappear

All configuration can only be redone

**Comment by Gary1567** [comment] 2023-01-13 06:25
me too

**Comment by gexxx05** [comment] 2023-01-17 07:26
Same here, all connections and configurations are gone.

**Comment by ManuelReschke** [comment] 2023-01-19 13:41
Has this something to do with that? https://github.com/Eugeny/tabby/issues/5370

**Comment by Eugeny** [comment] 2023-02-04 08:50
Duplicate of #5355

**Closed by Eugeny** 2023-02-04 08:50 UTC
Labels: T: Bug
