### ISSUE TITLE
Language options 

### ISSUE THREAD

**Issue by shuncon** [Eugeny/tabby#4792] opened 2021-10-19 06:02 UTC
Does not support Chinese, this is a feature that is missing 

I have been searching for a long time and haven't found the option to set Chinese

**Comment by psyuhen** [comment] 2021-10-19 07:18
兄弟，真没有。

**Comment by psyuhen** [comment] 2021-10-24 02:39
> need chinese

不需要吧

**Comment by Eugeny** [comment] 2021-12-06 08:16
Duplicate of #2538

**Closed by Eugeny** 2021-12-06 08:16 UTC
