### ISSUE TITLE
Unwanted config reset

### ISSUE THREAD

**Issue by WrongTeck** [Eugeny/tabby#5370] opened 2022-01-03 13:28 UTC
Hello, i found a new bug with Tabby

**Describe the problem**:
When increasing or decreasing the number of recent profiles to show int the Advanced tab of Profiles, the config resets to its default.
**To Reproduce**:
Go to Settings >  Profiles & Connections > Advanced
Click fast 3-4 times the arrows keys.
The config is now to its default.

OS: 
  Garuda Linux, tried also on Windows 10
  Version: 1.0.169
  Platform: Linux x64 5.15.12-zen1-1-zen
  Plugins: fit-screen, docker
  Frontend: xterm

Bye

**Comment by fddn** [comment] 2022-01-05 08:13
Same issue on restart. If I close the program, then restart it, config has been set back to default (profiles are missing, appearance, color scheme has been deleted, etc).

**Comment by MatthewCushing** [comment] 2022-10-30 02:15
> Same issue on restart. If I close the program, then restart it, config has been set back to default (profiles are missing, appearance, color scheme has been deleted, etc).
> 
> Even when I manually copy and restore the default config file, still not working....

I have same issue, doesn't even have to restart the application.  While I'm trying to set config settings back to what they were, it will change back to defaults while I'm modifying them.  I thought this was an issue with a settings sync plugin pulling in the defaults that it started with.  Turns out it has nothing to do with 3rd party config setting syncs.  It could be the native Config Sync.  Whatever it is, I can't fix it atm and don't have time to dig further into it.  It makes the terminal unusable.

**Comment by ManuelReschke** [comment] 2023-01-19 12:50
I have exactly the same problem. After **restarting** tabby I **lost** all my configured ssh connections. It's like a **reset**.
* option config encryption: true

I think this is a bad bug and make the whole terminal unusable.

**Comment by Eugeny** [comment] 2023-02-04 08:50
Duplicate of #5355

**Closed by Eugeny** 2023-02-04 08:50 UTC
Labels: T: Bug
