### ISSUE TITLE
Can't type ~ character

### ISSUE THREAD

**Issue by Orabig** [Eugeny/tabby#4458] opened 2021-08-21 08:33 UTC
Version: 1.0.155
Platform: Windows x64 10.0.19042
Plugins: none
Frontend: xterm

Some keys can't be used on a standard french keyboard.
One of the most useful of them is "~" which is AltGr+2, and it gives "é" instead of "~"

**Comment by Orabig** [comment] 2021-08-21 08:49
After a little research, it seems that it's a duplicate of (hold your breath...)
#3324 
#2866
#1373
#768

Seriously, there is even not a workaround for this ?

**Comment by enodr** [comment] 2021-08-21 09:19
I found out that Visual Studio Code terminal has the same bug. As both are using xterm.js could it be that the bug is in xterm.js?

**Comment by Bloopps** [comment] 2021-08-21 21:55
Same here https://github.com/Eugeny/tabby/issues/4433

**Comment by Eugeny** [comment] 2021-08-22 15:41
Duplicate of #768

**Closed by Eugeny** 2021-08-22 15:41 UTC
