### ISSUE TITLE
ALT-gr + ü writes ü instead of the intended ~ in my keyboard. 

### ISSUE THREAD

**Issue by osbama** [Eugeny/tabby#2866] opened 2020-08-07 11:37 UTC
Version: 1.0.115
Platform: win32 10.0.19041
Plugins: none

Keyboard TR-Q

**Comment by fluxtendu** [comment] 2020-08-15 09:38
I have the same issue with `ALT-gr+é` that write "é" instead of "~" (french keyboard layout)

I've made some tests that maybe can help:
`ALT-gr+é` x2 write `éé~` instead of `~~`
`ALT-gr+é` before `a` write `éã` instead of `ã`
`ALT-gr+é` before `b` write `ébb` instead of `~b`

`CTRL+ALT+é` x2 write `~~` as it should
`CTRL+ALT+é` before `a` write `ã` as it should
`CTRL+ALT+é` before `b` write "bb" instead of "~b"

**Comment by Nyxtorm** [comment] 2020-12-11 13:42
Hello,

I see that the problem is still there today.

We can add to the previous french azerty list :

`ALT-GR+è` x2 write ``èè` `` instead of  ``` `` ``` as it should

**Comment by enodr** [comment] 2021-03-10 15:14
Hi,

I can confirm there is a bug with the French AZERTY Layout.

FYI ALT-gr+é is a special key modifier that needs a second key input to print a character. 
ALT-gr+é+ space = ~
ALT-gr+é+ n = ñ
etc.

Same for the backtick. The backtick needs a second key press to print a character:
ALT-gr+è+ space = `
ALT-gr+è+ a = à
etc.

The behavior is the same for the caret key / ¨ key (which are one physical key, no need for alt-gr) **BUT these keys work as expected in Terminus**:
^+space = ^
¨ + space = ¨
^ + a = â
etc

What I don't understand is why Terminus has a problem with these key inputs has it is (should be?) handheld by Windows OS itself ?

Fixing this bug would be nice because under Linux ~ and ` are used quite often and this is the only very annoying bug I have currently in Terminus.

Regards.

**Comment by Eugeny** [comment] 2021-08-22 15:41
Duplicate of #768

**Closed by Eugeny** 2021-08-22 15:41 UTC
