### ISSUE TITLE
add profile failed

### ISSUE THREAD

**Issue by championjing** [Eugeny/tabby#4314] opened 2021-08-02 01:29 UTC
when I click new profile btn, using ssh connection template, type in info, then click save btn. there is not my new profile in profiles window.
![捕获](https://user-images.githubusercontent.com/19551593/127792804-00d75bcd-a7bb-4044-9d57-920b6b3d8091.PNG)
![捕获2](https://user-images.githubusercontent.com/19551593/127792808-5e8d98fd-e592-4d67-b6b7-f4ad1ad119a4.PNG)

**Comment by nevotheless** [comment] 2021-08-03 15:26
Duplicate of #4330 I think.

**Comment by Eugeny** [comment] 2021-08-03 17:13
Duplicate of #4330

**Closed by Eugeny** 2021-08-03 17:13 UTC
