### ISSUE TITLE
compile -> build linux deb file won't start

### ISSUE THREAD

**Issue by boonkerz** [Eugeny/tabby#5466] opened 2022-01-13 12:52 UTC
yarn start works but when i building
with: ./scripts/build-linux.js
the deb file and install those it won't start.

'''Unhandled Promise rejection: Cannot find module '@angular/common/locales/en-GB'
Require stack:
- /home/thomas/projekte/tabby/dist/linux-unpacked/resources/builtin-plugins/tabby-core/dist/index.js
- /home/thomas/projekte/tabby/dist/linux-unpacked/resources/app.asar/dist/index.html ; Zone: <root> ; Task: null ; Value: Error: Cannot find module '@angular/common/locales/en-GB'
Require stack:'''

**Comment by Eugeny** [comment] 2022-01-13 13:25
This is caused by the recent localization changes - should be fixed now.

**Closed** 2022-01-13 13:25 UTC
Labels: T: Bug
