### ISSUE TITLE
[Feature Request] As opposed to split pane, allow multiple panes / ability to drag an existing tab side by side with another tab

### ISSUE THREAD

**Issue by MostHated** [Eugeny/tabby#4222] opened 2021-07-18 18:51 UTC
Hey there,
    Far too often I find myself working in a tab, then need to connect somewhere else, so I just quickly open a new tab, but then after a while need to compare two things side by side, so I end up having to open a new instance of Termin..err, Tabby (still getting used to that, lol) altogether so I can have them side by side. I would love to be able to just grab my original tab and move it side-by-side next to my original, in a manner similar to Jetbrains IDE's/VSCode windows.
 

<details>
<summary>Example</summary>

![](https://i.imgur.com/1uyG1tH.gif)

</details>

Thanks,
-MH

**Comment by GanapathyRaman** [comment] 2021-07-19 13:26
The proposed method of drag and dropping to the side of any existing tab is much easier and useful when compare to the existing way.

**Comment by Eugeny** [comment] 2021-07-21 21:01
Duplicate of #1347 - done

**Closed by Eugeny** 2021-07-21 21:01 UTC
