### ISSUE TITLE
chinese

### ISSUE THREAD

**Issue by happy0824** [Eugeny/tabby#5286] opened 2021-12-24 06:49 UTC
Version: 1.0.169
Platform: Windows x64 10.0.19042
Plugins: none
Frontend: xterm

when  Query log  ,Chinese show unidentifiably scrambled 。we need encoding GBK and utf-8.
the same with input

**Comment by Eugeny** [comment] 2022-05-17 06:10
Duplicate of #2995

**Closed by Eugeny** 2022-05-17 06:10 UTC
