### ISSUE TITLE
suddenly loss all ssh connections!!!!

### ISSUE THREAD

**Issue by whybeyoung** [Eugeny/tabby#7874] opened 2023-02-02 06:29 UTC
wtf.  loss the all ssh connections...

**Describe the problem**:
[A clear and concise description of what the bug is.]

**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by birkanozer** [comment] 2023-02-03 17:11
The same thing happened to me too. Today I added a new SSH config. I selected a key from Vault. After I try to connect to the server, all configs was deleted and returned default except Vault content, which persisted.

**Comment by birkanozer** [comment] 2023-02-03 17:35
I tried a few times more to find the root cause. I discovered that it deletes the config file while the "Host key verification" modal shows up.

**Comment by Eugeny** [comment] 2023-02-04 08:50
Thanks @birkanozer for the first time I've been able to reproduce this with your description! I have a potential fix in https://github.com/Eugeny/tabby/actions/runs/4090823677 

I'll close this issue in favour of #5355 to keep it all in one place

**Closed by Eugeny** 2023-02-04 08:50 UTC
Labels: T: Bug
