### ISSUE TITLE
Adding multilingual support can make the software more usable！Such as chinese！

### ISSUE THREAD

**Issue by Trump-Shuai** [Eugeny/tabby#5385] opened 2022-01-04 16:52 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Eugeny** [comment] 2022-01-04 19:16
Duplicate of #2538

**Closed by Eugeny** 2022-01-04 19:16 UTC
