### ISSUE TITLE
AltGr+4 prints the "4" before the actual character "~" (Spain's Spanish layout)

### ISSUE THREAD

**Issue by oresot** [Eugeny/tabby#3324] opened 2021-01-11 09:27 UTC
This is not a new issue, has been there for almost a year.

With my layout I need to press AltGr+4 to print the "~" character, it works like any other tilde, the 1st press doesn't print anything, in case you want to put the character on top of a letter (ie: ã ñ) and the second press should be an space for the empty tilde or the letter. Pressing AltGr+4 twice will print "~~".

So this is how it works with Terminus:

```
1st press:  "4". Expected: nothing

2nd press (on Space key): "4~" (the 4 was printed with the 1st press). Expected: "~"
2nd press (on AltGR+4): "44~" (the first 4 was printed with the 1st press). Expected: "~~" 
```

Is the only one with this behaviour, other like ^ ¨ ´ ` work as expected.

**Comment by enodr** [comment] 2021-03-24 11:23
I confirm, same problem on FR AZERTY keyboard.

Duplicate of https://github.com/Eugeny/terminus/issues/2866

**Comment by devngl** [comment] 2021-06-26 15:26
Same happening for me on a brand new installation. Any workaround?

**Comment by enodr** [comment] 2021-06-27 10:11
> Same happening for me on a brand new installation. Any workaround?

Not yet, I confirm latest version still has this bug. Very annoying for non qwerty keyboard users.

**Comment by Eugeny** [comment] 2021-08-22 15:41
Duplicate of #768

**Closed by Eugeny** 2021-08-22 15:41 UTC
