### ISSUE TITLE
The serial port name does not support Chinese display

### ISSUE THREAD

**Issue by Secrets7s** [Eugeny/tabby#6200] opened 2022-04-19 06:20 UTC
Version: 1.0.174
Platform: Windows x64 10.0.19042
Plugins: none
Frontend: xterm

![image](https://user-images.githubusercontent.com/54909859/163938568-3d3db1b6-17d4-47b1-89d2-1072f15c95cb.png)

**Comment by ysc3839** [comment] 2022-04-19 13:05
Personally guess caused by this code: https://github.com/serialport/bindings-cpp/blob/4a4acbaf5ce37323722a02f93e7c8cb1029a7eea/src/serialport_win.cpp#L856
It doesn't use Unicode (UTF-16) version of system API. The returned string is likely encoded using GBK.
Since Windows 10 1903, this issue can be easily resolved by changing app's code page to UTF-8. ([Link](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#activecodepage)) But on earlier OS, only by using Unicode APIs can resolve.

**Closed** 2022-04-30 18:16 UTC
