### ISSUE TITLE
Can it support Duplicate SSH channel function like xshell

### ISSUE THREAD

**Issue by peitianwang** [Eugeny/tabby#5281] opened 2021-12-24 02:32 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhangyulu** [comment] 2022-01-15 09:31
That's exactly what I want. In some companies, we connect to servers through dynamic tokens like google authenticator. Without duplicating ssh channel, we have to input that dynamic tokens every time we start a new tab. Looking forward the  feature of duplicating ssh channel.

**Comment by Eugeny** [comment] 2022-01-15 11:28
Duplicate of #4795

It's already available in the nightly builds (you need to enable it in the profile settings).

**Closed by Eugeny** 2022-01-15 11:28 UTC
