### ISSUE TITLE
Configuration file (config.yaml) gets erased, tabby won't start properly

### ISSUE THREAD

**Issue by BernardoPilarz** [Eugeny/tabby#4306] opened 2021-07-30 11:59 UTC
I have tabby installed in Windows 10.

I am not sure of the circumstances that lead to this situation, but it has happened to me more than once.

On some occasions, Tabby will refuse to start properly. Four processes start in the background (and are visible in the task manager), but the Tabby window will not appear.
On further analysis, I found out that the 'config.yaml' file in '%AppData%/tabby' was completely empty (0 bytes in size).

Deleting the (empty) 'config.yaml' file will restore the application, but - obviously - cause the configuration to be lost.

For the moment I am handling this problem by keeping a backup of the configuration file.

**Comment by washicjr** [comment] 2021-07-30 13:36
I'm experiencing the same issue.

**Comment by pascal-mack** [comment] 2021-07-30 13:56
Same issue

**Comment by Eugeny** [comment] 2021-07-30 14:37
Which version are you on? I've first heard of this problem in regard to the latest (v149) release which I've immediately taken down. Could you please grab the latest nightly and see if the problem is fixed now?

**Comment by BernardoPilarz** [comment] 2021-07-30 14:56
I've experienced this in v148. I have then updated to v149 and kept experiencing this problem.

I'm going to install the latest nightly and let you know it it happens again.

**Comment by BernardoPilarz** [comment] 2021-07-30 15:05
I've installed v150 and the issue has happened again.

It looks like tabby just crashed.
Not 100% sure because I did not have tabby in the foreground when it happened (I'm not sure if I had closed the application or just sent it to the background).

When I started Tabby again, the app's window would not appear, and the config.yaml file was empty.

I've restored config.yaml from my backup and now it's working.

I'll keep using v150 and report any further problems.

**Comment by github123212321** [comment] 2021-07-30 15:15
Well I installed the nightly version minutes ago,then delete the empty C:\Users\XXX\AppData\Roaming\tabby then start Tabby.

Everything is working perfect.

**Comment by BernardoPilarz** [comment] 2021-07-30 15:24
It is now happening quite consistently.

If I add a new profile (SSH connection, using the vault to store passwords and/or keys), the config.yaml file gets erased as soon as I close Tabby.

**Comment by BernardoPilarz** [comment] 2021-07-30 15:27
I've now managed to have Tabby NOT delete the configuration file, by first deleting everything I found in the %AppData%\tabby folder, as suggested by @github123212321

**Comment by washicjr** [comment] 2021-07-30 15:43
I deleted the folder in the %appdata%\roaming folder and that kept the config.yaml file from being emptied on application close. HOWEVER, when I made a change to the configuration the config.yaml DID empty upon close of the application Clarence Washington Jr. Sent from my mobile device. Please excuse the brevity, any typos, or any misspellings that may be found in this message. Thank you. From: BernardoPilarzSent: Friday, July 30, 2021 10:27 AMTo: Eugeny/tabbyCc: Clarence Washington; CommentSubject: Re: [Eugeny/tabby] Configuration file (config.yaml) gets erased, tabby won't start properly (#4306) I've now managed to have Tabby NOT delete the configuration file, by first deleting everything I found in the %AppData%\tabby folder, as suggested by @github123212321—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Eugeny** [comment] 2021-07-31 13:23
Thanks for checking. I'll close this ticket as there's already discussion in an older report in #4293

**Closed by Eugeny** 2021-07-31 13:23 UTC
