### ISSUE TITLE
This software is opened and closed once on the linux system, and then it cannot be opened again.

### ISSUE THREAD

**Issue by goophps** [Eugeny/tabby#5734] opened 2022-02-12 06:54 UTC
This software is opened and closed once on the linux system, and then it cannot be opened again.
My linux distribution is deepin. I found out that the reason is that when I close the software, there are still several system processes, and I have to kill these processes manually to open the software again.

**Comment by Eugeny** [comment] 2022-02-12 09:05
Duplicate of #5733

**Closed by Eugeny** 2022-02-12 09:05 UTC
Labels: T: Bug
