### ISSUE TITLE
Tilda (~) not printed correctly when used as accent key.

### ISSUE THREAD

**Issue by mkielar** [Eugeny/tabby#1373] opened 2019-08-09 19:37 UTC
I'm using so called _"Polish Programmer"_ keyboard, where `Right Alt` is the accent key, so that `Alt + L` prints `Ł`, etc. Also, with this keyboard, the tilda `(~)` is also an accent character, so I usually need to press it twice to print it. However if I press it once, it doesn't print anything, but just waits for another keypress. If that another key is e.g. `/` then it prints both characters at once - i.e. `~/`.

At least that's how it works everywhere. Except terminus.
In terminus when I press `~`, and then `/` what gets printed on screen is `//`.

This is utterly annoying as navigation to and relative to home directory requires some awkward keypresses in terminus.

This is on Windows 10, with WSL.

**Comment by mkielar** [comment] 2019-10-08 20:20
Hmm, that's so very uncool @stale bot. Bump, then. Bumpy bump bump.

**Comment by rrerolle** [comment] 2020-04-09 18:07
I have the same problem with a French keyboard, where tilda is a combination of AltGr+2 ... which produces the character é in Terminus. Another broken combination is AltGR+7, which produces è instead of the expected ` (back quote). Other AltGr combinations do work fine.

**Comment by Eugeny** [comment] 2021-08-22 15:41
Duplicate of #768

**Closed by Eugeny** 2021-08-22 15:41 UTC
Labels: T: Bug, S: Confirmed, OS: Windows
