### ISSUE TITLE
Focus all tabs command

### ISSUE THREAD

**Issue by zong400** [Eugeny/tabby#5026] opened 2021-12-02 09:38 UTC

**Comment by Eugeny** [comment] 2021-12-02 09:39
When SSH sessions are open as panes within one tab, you can use the "focus all panes" hotkey to type/paste into all panes simultaneously.

**Comment by zong400** [comment] 2021-12-03 02:23
thx，but that way can't handle too much sessions. "focus all tabs" will be better.

**Comment by Eugeny** [comment] 2022-11-01 16:17
Duplicate of #5193

**Closed by Eugeny** 2022-11-01 16:17 UTC
Labels: T: Enhancement
