### ISSUE TITLE
I want to have a box that stores text to store my note information

### ISSUE THREAD

**Issue by IamJasonBoy** [Eugeny/tabby#8358] opened 2023-05-04 06:41 UTC
When I configure each SSH connection, I want to have a box that stores text to store my note information. I can record what this SSH does, what projects, and so on. And when synchronizing account information, also carry this content with you

**Comment by Eugeny** [comment] 2023-05-04 21:40
Duplicate of #5209

**Closed by Eugeny** 2023-05-04 21:40 UTC
