### ISSUE TITLE
About the text coding

### ISSUE THREAD

**Issue by murongxu** [Eugeny/tabby#6441] opened 2022-05-17 06:08 UTC
Version: 1.0.174
Platform: Windows x64 10.0.19044
Plugins: none
Frontend: xterm

Hello,
Could you add a option that user can set the text coding when use the SSH?
For some reasons, I can't modify the settings of the server, but there will be Japanese content on the server,
And sometimes I need to view these Japanese contents on the console.
Thank you

**Comment by Eugeny** [comment] 2022-05-17 06:10
Duplicate of #2995

**Closed by Eugeny** 2022-05-17 06:10 UTC
