### ISSUE TITLE
Make showing recent connections in profile tab as configurable so users can suppress if wanted

### ISSUE THREAD

**Issue by dhrxyz** [Eugeny/tabby#4247] opened 2021-07-22 02:54 UTC
some of us find it painful to see this random last few connection showing up on top, whereas in previous versions we could simply do hotkey->open panel go down 3rd or 4th for our servers, its just muscle memory

now we have all these random showing up one has to always look and figure out where to go.. Please please do allow for this option of "show recent connections at top" as configurable in profile tab, so people like us could suppress it. Thank you so much.

donated 10USD for a beer or two! thanks

**Comment by Eugeny** [comment] 2021-07-22 06:54
Duplicate of #4230

**Closed by Eugeny** 2021-07-22 06:54 UTC
