### ISSUE TITLE
Double clicking text blocks like the output of `grep -Irn` includes colons unlike all other terminals I've used

### ISSUE THREAD

**Issue by mboeker** [Eugeny/tabby#9828] opened 2024-07-31 06:02 UTC
**Problem**:
Double clicking results like the output of `grep -Irn` also selects the colon before the line number unlike all other terminals. For example:
```
ubuntu@server:~$ sudo grep -Irn blackbox /etc/kolla/
/etc/prometheus-server/prometheus.yml:109:  job_name: blackbox_exporter
/etc/prometheus-blackbox-exporter/config.json:5:            "source": "/var/lib/kolla/config_files/prometheus-blackbox-exporter.yml",
/etc/prometheus-blackbox-exporter/config.json:6:            "dest": "/etc/prometheus/blackbox.yml",
```
In all terminals that I've used, double clicking on the path in any of those grep results will highlight just the path.

So in other terminals, double clicking this block anywhere in the path:
`/etc/prometheus-blackbox-exporter/config.json:6:`
Selects this text:
`/etc/prometheus-blackbox-exporter/config.json`

but in Tabby, it selects the whole block, including `:6:`

This isn't a real bug since I doubt there are clear guidelines on what should be highlighted on doubleclick, but it is an inconvenience and a deviation from other terminals.

**To Reproduce**: Doubleclick lines with colons `:` in them.

**Comment by Eugeny** [comment] 2024-08-01 09:41
Duplicate of #9831

**Closed by Eugeny** 2024-08-01 09:41 UTC
Labels: T: Bug
