### ISSUE TITLE
Segmentation fault on startup

### ISSUE THREAD

**Issue by koterpillar** [Eugeny/tabby#4424] opened 2021-08-16 10:32 UTC
Version: 1.0.153
Platform: macOS x64 19.6.0
Plugins: none
Frontend: xterm

I've removed the configuration (`~/Library/Application Support/Tabby`) completely and getting this on startup via terminal:

```
(node:72935) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Tabby Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
(node:72935) Electron: Loading non-context-aware native module in renderer: '/var/folders/dh/05d9pgq9703g3hf5c347v8qjp00nn6/T/.org.tabby.msJYO7'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[1]    72930 segmentation fault  /Applications/Tabby.app/Contents/MacOS/Tabby
```

**Comment by koterpillar** [comment] 2021-08-16 10:33
`--debug` opens a Web Tools, but doesn't help otherwise - Tabby still crashes.

**Comment by Eugeny** [comment] 2021-08-16 11:02
Could you please check if a Crash Report is generated in the Console.app?

**Comment by koterpillar** [comment] 2021-08-16 11:22
Nothing, but there is a dump in `/Users/akotlyarov/Library/Application Support/tabby/Crashpad/completed`.
[d580ea07-0c81-4b04-a4d0-35816cdcceef.dmp.gz](https://github.com/Eugeny/tabby/files/6991930/d580ea07-0c81-4b04-a4d0-35816cdcceef.dmp.gz)

**Comment by Eugeny** [comment] 2021-08-16 11:50
Duplicate of #4422

**Closed by Eugeny** 2021-08-16 11:50 UTC
