### ISSUE TITLE
Windows 10 Enterprise Windows 10 Pro run tabby window black window, can't see any menu,

### ISSUE THREAD

**Issue by godaizhan** [Eugeny/tabby#8882] opened 2023-08-29 07:04 UTC
**Describe the problem**:
I run two versions
tabby-1.0.198-portable-x64.zip
tabby-1.0.198-setup-x64.exe

I run tabby window black window in Windows 10 Enterprise Windows 10 Pro and can't see any menu,

**To Reproduce**:
[Steps to reproduce the behavior]
![image](https://github.com/Eugeny/tabby/assets/103105164/357167b0-092e-4793-b01c-73437a44f8f0)
![image](https://github.com/Eugeny/tabby/assets/103105164/12f26d67-ada3-4698-ba7a-69fca0044228)

There is no error

**Comment by Eugeny** [comment] 2023-08-29 07:05
Duplicate of #8868

**Comment by Eugeny** [comment] 2023-08-29 07:18
Duplicate of #8868

**Closed by Eugeny** 2023-08-29 07:18 UTC
Labels: T: Bug
