### ISSUE TITLE
Latest version display problem

### ISSUE THREAD

**Issue by foowaa** [Eugeny/tabby#4939] opened 2021-11-16 09:37 UTC
As is shown below:
![Snipaste_2021-11-16_17-32-24](https://user-images.githubusercontent.com/11385319/141959778-49f48c84-4479-4f45-a0f4-9cc5dbefd895.png)

The [close] [min] [max] button is not correct.

OS: win10

**Comment by Eugeny** [comment] 2021-11-16 10:07
Duplicate of #4926

**Closed by Eugeny** 2021-11-16 10:07 UTC
